
---
- hosts: localhost
  vars_files:
    - vars.yml
  vars:
    force: false
  tasks:
    - debug: msg={{force}}
    - name: "build services. push docker images"
      include: each_service/build.yml
      with_items: "{{services}}"

- hosts: manager
  remote_user: root
  vars_files:
    - vars.yml
    - vars.credentials.yml
  tasks:
    - include: each_service/deploy.yml
      with_items: "{{services}}"

