---
# TODO: deal with multi-manager
- hosts: manager
  vars_files:
    - vars.yml
    - vars.credentials.yml
  tasks:
    - debug: msg={{groups}}
    - command: "docker swarm init"
      ignore_errors: yes
    - name: Retrive worker token
      command: "docker swarm join-token worker -q"
      register: join_token_out
    - set_fact: join_token={{join_token_out.stdout}}
    - debug: msg={{join_token}}
    - command: "docker login -p {{registry_pass}} -u {{registry_user}} registry.mif.io"
- hosts: workers
  tasks:
    - set_fact: join_token={{hostvars[groups.manager[0]].join_token}}
    - set_fact: join_host={{groups.manager[0]}}
    - name: join node
      command: "docker swarm join --token {{join_token}} {{join_host}}:2377"


